name: Terraform Deploy en LocalStack

on:
  push:
    branches: [ master ]

jobs:
  terraform:
    runs-on: ubuntu-latest
    services:
      localstack:
        image: localstack/localstack
        ports:
          - 4566:4566
        options: --health-cmd="curl -f http://localhost:4566/_localstack/health || exit 1" --health-interval=5s --health-timeout=2s --health-retries=20
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
